[build-system]
    requires      = ["Cython>=3,<4", "setuptools>=64"]
    build-backend = "setuptools.build_meta"

[project]
    name = "pyenet-dlts"
    version = "1.5"
    description = "A fork of pyenet with DLTS support"
    readme = "README.rst"
    license = "BSD-3-Clause"
    requires-python = ">=3.9"
    maintainers = [
        {name = "malakai gunderson", email = "kaifungamedev@gmail.com"},
    ]

[tool.setuptools]
    py-modules = []

    [project.urls]
        Homepage   = "https://github.com/kaifungamedev/pyenet-dlts/"
        Repository = "https://github.com/kaifungamedev/pyenet-dlts/"


[tool.cibuildwheel]
    build = "cp*"
    skip  = "cp38-* *-win32 *-musllinux_*"

    [tool.cibuildwheel.linux]
        before-all = "yum install -y openssl-devel || dnf install -y openssl-devel || apt-get install -y libssl-dev || true"

    [tool.cibuildwheel.windows]
        before-all = "vcpkg install openssl:x64-windows openssl:arm64-windows"

    [tool.cibuildwheel.macos]
        before-all = "brew install openssl"
        [tool.cibuildwheel.macos.environment]
            PKG_CONFIG_PATH          = "$(brew --prefix openssl)/lib/pkgconfig"
            MACOSX_DEPLOYMENT_TARGET = 15.0
            LDFLAGS                  = "-L$(brew --prefix openssl)/lib"
            CPPFLAGS                 = "-I$(brew --prefix openssl)/include"
